export const serverUrl = "https://mmdsz-tdk-functions.vercel.app/api";

export const universityList = [
  "",
  "MOGYTTE",
  "SE",
  "DE",
  "PTE",
  "SZTE",
  "Egyéb",
];

export const sectionList = [
  "",
  "Általános Belgyógyászat",
  "Általános Orvosi Asszisztens",
  "Általános Sebészet",
  "Anatómia és Patológia",
  "Aneszteziológia És Intenzív Terápia",
  "Angiológia",
  "Bioinformatika",
  "Bőrgyógyászat",
  "Diabetológia",
  "Egészségügyszervezés",
  "Élettan",
  "Endokrinológia",
  "Farmakológia",
  "Fogorvostudomány",
  "Fül-Orr-Gégészet",
  "Gasztroenterológia",
  "Genetika",
  "Gyermekgyógyászat",
  "Gyógyszerészet",
  "Gyógytorna És Sporttudomány",
  "Hematológia",
  "Idegsebészet",
  "Imagisztika",
  "Infektológia",
  "Kardiológia",
  "Kórélettan",
  "Labordiagnosztika",
  "Megelőző Orvostudomány És Népegészségtan",
  "Mikrobiológia",
  "Neurológia",
  "Nőgyógyászat",
  "Onkológia",
  "Ortopédia",
  "Poszter Szekció",
  "Pszichiátria És Viselkedéstan",
  "Reumatológia",
  "Szemészet",
  "Traumatológia",
  "Urológia",
] as const;
