export const serverUrl = "https://mmdsz-tdk-functions.vercel.app/api";

export const universityList = [
  "",
  'Marosvásárhelyi "George Emil Palade" Orvosi, Gyógyszerészeti, Tudományos és Technológiai Egyetem',
  "Semmelweis Egyetem",
  "Debreceni Egyetem",
  "Pécsi Tudomány Egyetem",
  "Szegedi Tudomány Egyetem",
  "Sapientia Erdélyi Magyar Tudományegyetem",
];

export const sectionList = [
  "",
  "Általános Belgyógyászat",
  "Angiológia",
  "Általános Orvosi Asszisztens",
  "Általános Sebészet Anatómia",
  "Patológia",
  "Aneszteziológia És Intenzív Terápia",
  "Bőrgyógyászat",
  "Diabetológia",
  "Élettan",
  "Kórélettan",
  "Fogorvostudomány",
  "Fül-Orr-Gégészet",
  "Gasztroenterológia",
  "Gyermekgyógyászat",
  "Gyógyszerészet",
  "Infektológia",
  "Kardiológia",
  "Megelőző Orvostudomány És Népegészségtan",
  "Mikrobiológia",
  "Neurológia",
  "Idegsebészet",
  "Nőgyógyászat",
  "Ortopédia",
  "Traumatológia",
  "Pszichiátria És Viselkedéstan",
  "Imagisztika",
  "Reumatológia",
  "Szemészet",
  "Urológia",
  "Farmakológia",
  "Labordiagnosztika",
  "Endokrinológia",
  "Hematológia",
  "Gyógytorna És Sporttudomány",
  "Bioinformatika",
  "Genetika",
  "Onkológia",
  "Egészségügyszervezés",
  "Poszter Szekció",
  "Egyéb"
];
